export let logoImg = '../src/images/logo.svg'
export let headerItems = [
    {
        id: '2',
        img: '../src/images/datarkLike.png',
        title: "Liked"
    },
    {
        id: '3',
        img: '../src/images/cart.png',
        title: "Cart"
    },
    {
        id: '1',
        img: '../src/images/login.png',
        title: "Sign In"
    }
]
export let SliderImages = [
    "../src/images/sliderImg3.png",
    "../src/images/sliderImg1.png",
    "../src/images/sliderImg2.JPG",
]


export let products = [
    {
        id: '1',
        type: "electronic",
        img: '../src/images/electronicImg1.jpg',
        title: 'House of electronics / DVR car mirror 3 in 1',
        price: '1 319₽',
        discount: '4 285₽',
        stars: '4.5',
        bought: 122,
        Bestseller: false,
        top: false

    },
    {
        id: '2',
        type: "electronic",
        img: '../src/images/electronicImg2.jpg',
        title: 'Herler Electronics / Wireless silent mouse with battery and backlight',
        price: '349₽',
        discount: '1 590₽',
        stars: '4.4',
        bought: 234,
        Bestseller: true,
        top: false

    },
    {
        id: '3',
        type: "electronic",
        img: '../src/images/electronicImg3.jpg',
        title: 'AKENZY electronics / smart watch 8 series smart watch',
        price: '1 527₽',
        discount: '6 215₽',
        stars: '4.4',
        bought: 2355,
        Bestseller: false,
        top: false

    },
    {
        id: '4',
        type: "electronic",
        img: '../src/images/electronicImg4.jpg',
        title: 'S&H Electronics / Walkie-talkie play set',
        price: '1 500₽',
        discount: '7 915₽',
        stars: '4.3',
        bought: 4561,
        Bestseller: false,
        top: false

    },  
    {
        id: '5',
        type: "electronic",
        img: '../src/images/electronicImg5.jpg',
        title: '4-Electronics / LED sunset projector sunset lamp',
        price: '542₽',
        discount: '1 890₽',
        stars: '4.2',
        bought: 144,
        Bestseller: false,
        top: false

    },
    {
        id: '6',
        type: "electronic",
        img: '../src/images/electronicImg6.jpg',
        title: 'Normal Electronics Car/Car/Car phone charger holder',
        price: '1 260₽',
        discount: '2 265₽',
        stars: '4.6',
        bought: 1043,
        Bestseller: false,
        top: false

    },
    {
        id: '7',
        type: "electronic",
        img: '../src/images/electronicImg7.jpg',
        title: '7-electronics / Backlit Wireless Gaming Mouse',
        price: '355₽',
        discount: '2 490₽',
        stars: '4.2',
        bought: 8733,
        Bestseller: false,
        top: false

    },
    {
        id: '8',
        type: "electronic",
        img: '../src/images/electronicImg8.jpg',
        title: 'S&H Electronics / Car DVR with 3 in 1 camera',
        price: '2 007₽',
        discount: '4 310₽',
        stars: '4.2',
        bought: 12901,
        Bestseller: false,
        top: false

    },
    {
        id: '9',
        type: "electronic",
        img: '../src/images/electronicImg9.jpg',
        title: 'KRAINEV ELECTRONICS / Professional hair dryer with ionization',
        price: '3 977₽',
        discount: '17 539₽',
        stars: '4.6',
        bought: 16221,
        Bestseller: false,
        top: false

    },
    {
        id: '10',
        type: "electronic",
        img: '../src/images/electronicImg10.jpg',
        title: 'E.D.S Electronics / Floor dryer',
        price: '5 439₽',
        discount: '17 000₽',
        stars: '4.8',
        bought: 1321,
        Bestseller: false,
        top: false

    },
    {
        id: '11',
        type: "electronic",
        img: '../src/images/electronicImg11.jpg',
        title: 'S&H Electronics / Car DVR',
        price: '2 305₽',
        discount: '8 576₽',
        stars: '4.3',
        bought: 952,
        Bestseller: false,
        top: false

    },
    {
        id: '12',
        type: "electronic",
        img: '../src/images/electronicImg12.jpg',
        title: 'Roku Electronics / Wireless headphones for iPhone and Android bluetooth Air 2',
        price: '957₽',
        discount: '6 000₽',
        stars: '4.4',
        bought: 43225,
        Bestseller: false,
        top: false

    },
    {
        id: '13',
        type: "electronic",
        img: '../src/images/electronicImg13.jpg',
        title: '4-Electronics / Zoom Rechargeable LED Flashlight, Car, Home, Car Flashlight',
        price: '313₽',
        discount: '1 290₽',
        stars: '4.2',
        bought: 871,
        Bestseller: false,
        top: false

    },
    {
        id: '14',
        type: "electronic",
        img: '../src/images/electronicImg14.jpg',
        title: 'M-Electronics / Wireless Bluetooth Headphones with Mic',
        price: '803₽',
        discount: '2 080₽',
        stars: '4.3',
        bought: 12311,
        Bestseller: false,
        top: false

    },
    {
        id: '15',
        type: "electronic",
        img: '../src/images/electronicImg15.jpg',
        title: 'KRAINEV ELECTRONICS / Beard, mustache, eyebrow hair and nose trimmer with attachments',
        price: '2 457₽',
        discount: '6 500₽',
        stars: '4.4',
        bought: 3488,
        Bestseller: false,
        top: false

    },
    {
        id: '16',
        type: "electronic",
        img: '../src/images/electronicImg16.jpg',
        title: 'N-S Electronics / Surge Protector USB Extension Tee for Outlet',
        price: '615₽',
        discount: '1 890₽',
        stars: '4.4',
        bought: 1019,
        Bestseller: false,
        top: false
    },
    {
        id: '17',
        type: "shoes",
        img: '../src/images/shoesImg1.jpg',
        title: 'LA-shoes / Summer sneakers',
        price: '1 784₽',
        discount: '4 990₽',
        stars: '4.4',
        bought: 452,
        Bestseller: false,
        top: false
    },
    {
        id: '18',
        type: "shoes",
        img: '../src/images/shoesImg2.jpg',
        title: 'ZM SHOES / Nike SB Dunk Low "Mummy" Sneakers',
        price: '3 312₽',
        discount: '16 000₽',
        stars: '4.0',
        bought: 121,
        Bestseller: false,
        top: false
    },
    {
        id: '19',
        type: "shoes",
        img: '../src/images/shoesImg3.jpg',
        title: 'Ela Shoes / Sneakers for women summer sports',
        price: '972₽',
        discount: '1 989₽',
        stars: '4.6',
        bought: 2364,
        Bestseller: false,
        top: false
    },
    {
        id: '20',
        type: "shoes",
        img: '../src/images/shoesImg4.jpg',
        title: 'ZM SHOES / Sneakers 530 New balance',
        price: '3 881₽',
        discount: '18 780₽',
        stars: '4.0',
        bought: 5622,
        Bestseller: false,
        top: false
    },
    {
        id: '21',
        type: "shoes",
        img: '../src/images/shoesImg5.jpg',
        title: 'Ela Shoes / Sneakers for women summer sports',
        price: '972₽',
        discount: '1 989₽',
        stars: '4.6',
        bought: 2364,
        Bestseller: false,
        top: false
    },
    {
        id: '22',
        type: "shoes",
        img: '../src/images/shoesImg6.jpg',
        title: 'ZM SHOES / Sneakers',
        price: '517₽',
        discount: '2 500₽',
        stars: '4.0',
        bought: 13503,
        Bestseller: false,
        top: false
    },
    {
        id: '23',
        type: "shoes",
        img: '../src/images/shoesImg7.jpg',
        title: 'cross shoes / sneakers womens adidas sneakers adidas iniki',
        price: '1 793₽',
        discount: '3 999₽',
        stars: '4.3',
        bought: 4522,
        Bestseller: false,
        top: false
    },
    {
        id: '24',
        type: "shoes",
        img: '../src/images/shoesImg8.jpg',
        title: 'D.A. SHOES / Sneakers and sneakers for women summer sports white eco-leather',
        price: '1 679₽',
        discount: '10 100₽',
        stars: '4.5',
        bought: 11425,
        Bestseller: false,
        top: false
    },
    {
        id: '25',
        type: "shoes",
        img: '../src/images/shoesImg9.jpg',
        title: 'quality / shoes Womens platform sneakers',
        price: '1 073₽',
        discount: '3 500₽',
        stars: '4.5',
        bought: 7622,
        Bestseller: false,
        top: false
    },
    {
        id: '26',
        type: "shoes",
        img: '../src/images/shoesImg10.jpg',
        title: 'NiiN SHOES / Sneakers for mens summer breathable sports running leatherette',
        price: '2 217₽',
        discount: '4 900₽',
        stars: '4.4',
        bought: 12316,
        Bestseller: false,
        top: false
    },
    {
        id: '27',
        type: "shoes",
        img: '../src/images/shoesImg11.jpg',
        title: 'Dream Shoes / Sneakers PUMA Turin II',
        price: '1 708₽',
        discount: '6 500₽',
        stars: '4.2',
        bought: 6722,
        Bestseller: false,
        top: false
    },
    {
        id: '28',
        type: "shoes",
        img: '../src/images/shoesImg12.jpg',
        title: 'ZM SHOES / sneakers for men Nike Air Zoom Spiridon x Stussy',
        price: '4 450₽',
        discount: '21 500₽',
        stars: '4.0',
        bought: 23511,
        Bestseller: false,
        top: false
    },
    {
        id: '29',
        type: "clothing",
        img: '../src/images/clothingImg1.jpg',
        title: 'Am Clothing / Casual midi skirt',
        price: '1 609₽',
        discount: '4 320₽',
        stars: '4.5',
        bought: 10231,
        Bestseller: false,
        top: false
    },
    {
        id: '30',
        type: "clothing",
        img: '../src/images/clothingImg2.jpg',
        title: 'ChicChic Clothing / Classic Denim Pencil Skirt with Slit',
        price: '1 604₽',
        discount: '9 300₽',
        stars: '4.4',
        bought: 3455,
        Bestseller: false,
        top: false
    },
    {
        id: '31',
        type: "clothing",
        img: '../src/images/clothingImg3.jpg',
        title: 'Am Clothing / Casual midi skirt',
        price: '1 457₽',
        discount: '6 600₽',
        stars: '4.5',
        bought: 6428,
        Bestseller: false,
        top: false
    },
    {
        id: '32',
        type: "clothing",
        img: '../src/images/clothingImg4.jpg',
        title: 'Epifana Clothing Co. /  Womens palazzo trouser suit summer knitted noodles',
        price: '2 135₽',
        discount: '7 500₽',
        stars: '4.8',
        bought: 9811,
        Bestseller: false,
        top: false
    },
    {
        id: '33',
        type: "clothing",
        img: '../src/images/clothingImg5.jpg',
        title: 'Am Clothing / Casual midi skirt',
        price: '1 006₽',
        discount: '5 400₽',
        stars: '4.4',
        bought: 4262,
        Bestseller: false,
        top: false
    },
    {
        id: '34',
        type: "clothing",
        img: '../src/images/clothingImg7.jpg',
        title: 'Epifana Clothing Co. / Womens palazzo trouser suit summer knitted noodles',
        price: '2 080₽',
        discount: '7 500₽',
        stars: '4.8',
        bought: 9813,
        Bestseller: false,
        top: false
    },
    {
        id: '35',
        type: "clothing",
        img: '../src/images/clothingImg8.jpg',
        title: 'Vigore Clothing / Sports Summer Yoga Suit',
        price: '3 630₽',
        discount: '8 800₽',
        stars: '4.5',
        bought: 13413,
        Bestseller: false,
        top: false
    },
    {
        id: '36',
        type: "clothing",
        img: '../src/images/clothingImg9.jpg',
        title: 'Epifana Clothing Co. / Womens palazzo trouser suit summer knitted noodles',
        price: '2 080₽',
        discount: '7 500₽',
        stars: '4.8',
        bought: 9113,
        Bestseller: false,
        top: false
    },
    {
        id: '37',
        type: "phones",
        img: '../src/images/phoneImg1.jpg',
        title: 'Shumoff Silicone / Case for Apple iPhone 11 for iPhone 11',
        price: '197₽',
        discount: '3 710₽',
        stars: '4.7',
        bought: 45622,
        Bestseller: false,
        top: false
    },
    {
        id: '38',
        type: "phones",
        img: '../src/images/phoneImg2.jpg',
        title: 'Able case / Case for iPhone 11 transparent silicone for iPhone',
        price: '128₽',
        discount: '889₽',
        stars: '4.6',
        bought: 11242,
        Bestseller: false,
        top: false
    },
    {
        id: '39',
        type: "phones",
        img: '../src/images/phoneImg3.jpg',
        title: 'BEST CASE / Case for iPhone 11 for iPhone with logo',
        price: '912₽',
        discount: '2 000₽',
        stars: '4.5',
        bought: 5489,
        Bestseller: false,
        top: false
    },
    {
        id: '40',
        type: "phones",
        img: '../src/images/phoneImg4.jpg',
        title: 'case lab. / Case for iPhone 11 protective shockproof',
        price: '268₽',
        discount: '2 580₽',
        stars: '4.6',
        bought: 23673,
        Bestseller: false,
        top: false
    },
    {
        id: '41',
        type: "phones",
        img: '../src/images/phoneImg6.jpg',
        title: 'Apple / iPhone 14 Pro 256GB',
        price: '109 698₽',
        discount: '129 990₽',
        stars: '4.7',
        bought: 124,
        Bestseller: false,
        top: false
    },
    {
        id: '42',
        type: "phones",
        img: '../src/images/phoneImg7.jpg',
        title: 'Apple / iPhone 14 Pro 256GB',
        price: '109 698₽',
        discount: '129 990₽',
        stars: '4.7',
        bought: 124,
        Bestseller: false,
        top: false
    },
    {
        id: '43',
        type: "phones",
        img: '../src/images/phoneImg8.jpg',
        title: 'Apple / iPhone 14 Pro 256GB',
        price: '109 698₽',
        discount: '129 990₽',
        stars: '5',
        bought: 22,
        Bestseller: false,
        top: false
    },
    {
        id: '44',
        type: "phones",
        img: '../src/images/phoneImg9.jpg',
        title: 'Apple / iPhone 14 Pro 256GB',
        price: '109 698₽',
        discount: '129 990₽',
        stars: '4.7',
        bought: 124,
        Bestseller: false,
        top: false
    },
    {
        id: '45',
        type: "computers",
        img: '../src/images/computerImg1.jpg',
        title: 'Gigabyte / Notebook Gigabyte G5 GE [GE-51RU263SD]/15.6" FHD/RTX 3050',
        price: '57 706₽',
        discount: '69 990₽',
        stars: '4.7',
        bought: 240,
        Bestseller: false,
        top: false
    },
    {
        id: '46',
        type: "computers",
        img: '../src/images/computerImg2.jpg',
        title: 'Acer / Notebook Acer Nitro 5 AN515-45 R585SGN',
        price: '53 390₽',
        discount: '94 900₽',
        stars: '3.9',
        bought: 127,
        Bestseller: false,
        top: false
    },
    {
        id: '47',
        type: "computers",
        img: '../src/images/computerImg3.jpg',
        title: 'Air Ultra / Notebook N5095 IPS 15.6" FHD 16/512gb',
        price: '35 510₽',
        discount: '71 738₽',
        stars: '4.6',
        bought: 67,
        Bestseller: false,
        top: false
    },
    {
        id: '48',
        type: "computers",
        img: '../src/images/computerImg4.jpg',
        title: 'Infinix Inbook / Y1 PLUS 10-th XL28/15/Core-i5/8GB/512GB',
        price: '34 039₽',
        discount: '44 990₽',
        stars: '5',
        bought: 712,
        Bestseller: false,
        top: false
    },
    {
        id: '49',
        type: "computers",
        img: '../src/images/computerImg5.jpg',
        title: 'Acer Notebook / Acer Nitro 5 AN515-57 I785SGN (NH.QELER.005)',
        price: '64 340₽',
        discount: '99 000₽',
        stars: '4.4',
        bought: 213,
        Bestseller: false,
        top: false
    },
    {
        id: '50',
        type: "computers",
        img: '../src/images/computerImg6.jpg',
        title: 'Compolis / Notebook 15.6" IPS 4-Core 8GB SSD 256GB',
        price: '31 640₽',
        discount: '68 000₽',
        stars: '4.9',
        bought: 54,
        Bestseller: false,
        top: false
    },
    {
        id: '51',
        type: "computers",
        img: '../src/images/computerImg7.jpg',
        title: 'Acer Notebook / Acer Nitro 5 AN515-57 NH.QELER.00C',
        price: '69 387₽',
        discount: '92 900₽',
        stars: '3.6',
        bought: 184,
        Bestseller: false,
        top: false
    },
    {
        id: '52',
        type: "computers",
        img: '../src/images/computerImg8.jpg',
        title: 'Acer Notebook / Acer Aspire 3 A315-56/i3/8Gb/512Gb (NX.HS5ER.02E)',
        price: '27 483₽',
        discount: '45 700₽',
        stars: '5',
        bought: 34,
        Bestseller: false,
        top: false
    },
    {
        id: '53',
        type: "Home Appliances",
        img: '../src/images/homeImg1.jpg',
        title: 'Ketrarum / Home Mop with Wringer and Bucket for Mopping the Floor',
        price: '681₽',
        discount: '11 870₽',
        stars: '4.3',
        bought: 23411,
        Bestseller: false,
        top: false
    },
    {
        id: '54',
        type: "Home Appliances",
        img: '../src/images/homeImg2.jpg',
        title: 'ECO-HOME / Bed linen 2-bed Poplin',
        price: '1 694₽',
        discount: '4 978₽',
        stars: '4.5',
        bought: 2311,
        Bestseller: false,
        top: false
    },
    {
        id: '55',
        type: "Home Appliances",
        img: '../src/images/homeImg3.jpg',
        title: 'Home&Travel / Smart mop with wringer and floor bucket professional',
        price: '2 203₽',
        discount: '5 300₽',
        stars: '4',
        bought: 451,
        Bestseller: false,
        top: false
    },
    {
        id: '56',
        type: "Home Appliances",
        img: '../src/images/homeImg4.jpg',
        title: 'Arya home / collection Bedspread plaid on euro bed, sofa 230x250 with pillowcases',
        price: '3 696₽',
        discount: '23 398₽',
        stars: '4',
        bought: 311,
        Bestseller: false,
        top: false
    },
    {
        id: '57',
        type: "Home Appliances",
        img: '../src/images/homeImg5.jpg',
        title: 'HOME Clothes / hangers metal black 2pcs.',
        price: '390₽',
        discount: '523₽',
        stars: '4.8',
        bought: 3499,
        Bestseller: false,
        top: false
    },
    {
        id: '58',
        type: "Home Appliances",
        img: '../src/images/homeImg6.jpg',
        title: 'Carnero / Home Bathroom rug',
        price: '587₽',
        discount: '3 540₽',
        stars: '4.6',
        bought: 5618,
        Bestseller: false,
        top: false
    },
    {
        id: '59',
        type: "Home Appliances",
        img: '../src/images/homeImg7.jpg',
        title: 'u_project / home Mop with wringer and bucket for mopping and house cleaning',
        price: '984₽',
        discount: '2 000₽',
        stars: '4.3',
        bought: 421,
        Bestseller: false,
        top: false
    },
    {
        id: '60',
        type: "Home Appliances",
        img: '../src/images/homeImg8.jpg',
        title: 'HOME express / Shelving unit kraft oak white Pine, 33x33x174.6 cm',
        price: '1 354₽',
        discount: '3 678₽',
        stars: '4.9',
        bought: 1125,
        Bestseller: false,
        top: false
    },
]

export let Categories = [
    'Mobile Phones',
    'Computers',
    'Electronics',
    'Home Appliances',
    'Home Improvement & Tools',
    'Security & Protection',
    'Automobiles & Motorcycles',
    'Home, Garden & Office',
    'Furniture',
    'Clothing',
    "Shoes",
    'Accesories',
    'Luggage & Bags',
    'Sports & EntrTainment',
    'Mother & Kids',
    'Toys & hobbies',
    'Beauty & Helth',
    '18+',
    'Pet Products',
    'Food',
]